export const MODULE_ADDRESS = {
    DASHBOARD: 'dashboard',
    INSTRUCTOR_PANEL: 'instructorPanel',
    BOOKING: 'booking',
    ABOUT_US: 'about-us',
    SETTINGS: 'settings',
    AUTHENTICATION: 'auth'
}

export const MODULE_NAMES = {
    [MODULE_ADDRESS.DASHBOARD]: 'HOME',
    [MODULE_ADDRESS.INSTRUCTOR_PANEL]: 'INSTRUCTOR MODE',
    [MODULE_ADDRESS.SETTINGS]: 'SETTINGS',
    [MODULE_ADDRESS.BOOKING]: 'BOOKING',
    [MODULE_ADDRESS.AUTHENTICATION]: 'AUTHENTICATION',
    [MODULE_ADDRESS.ABOUT_US]: 'ABOUT US'
}